[networks]
name = "macvlan"

[nginx]
http_conf = "/home/docker/openresty/nginx/conf.d" # 根据自己的环境修改
stream_conf = "/home/docker/openresty/nginx/tcp.d" # 根据自己的环境修改
#conf = "/Users/limingze/GolandProjects/docker-tool/config/test" # 根据自己的环境修改
http_tpl = "config/nginx.http.tpl.conf"
stream_tpl = "config/nginx.stream.tpl.conf"
#tpl = "/Users/limingze/GolandProjects/docker-tool/config/nginx.tpl.conf"

[port_http]
ddns = "9876"
mtube = "8096"
jackett = "9117"
jf = "8096"
nastool = "3000"
nastool3 = "3000"
portainer = "9000"
wiz = "80"
yacd = "80"
clash = "9090"
csf = "19035"
qljd = "5700"
qlqd = "5700"
qiandao = "80"
adguardhome = "80"
bark = "8080"
embystat = "6555"
openresty = "80"
hm = "80"
book = "80"
nd = "4533"
live = "35455"
tv = "80"
hass = "8123"
wxedge = "18888"
fb = "80"
cups = "631"

[port_stream]
clash = ["7890","7891"] # 必须按照此格式配置 ["端口号","端口号"]
adguardhome = ["53","67","68","443","784","853","8853","5443"]
mariadb = ["3306"]